service: cirrent-interop

provider:
  name: azure
  runtime: nodejs14

functions:
  app:
    handler: src/app.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: function

plugins:
  - serverless-azure-functions